### ISSUE TITLE
updating model has a problem, when model has array of objectId;

### ISSUE THREAD

**Issue by anhoev** [florianholzapfel/express-restify-mongoose#294] opened 2016-07-12 12:48 UTC
E.g: 
Schema for employee: 

``` js
{
  name: {type: String, default: 'Employee'},
  company: [{type: mongoose.Schema.Types.ObjectId, ref: 'Company'}]
}
```

When an employee has two companies and I try to remove a company, so restify can not update the model.

i tried to change a little of source code (in **operation.js**) from:

``` js
var cleanBody = moredots(depopulate(req.body));
```

to: 

``` js
var cleanBody = req.body;
```

it will work ok.

``` js
moredots(depopulate(req.body))
```

Returns a result like :

``` js
company.0 = "574afe60bce5048b69e17b18"
```

instead of

``` js
company = ["574afe60bce5048b69e17b18"]
```

I think there is a problem in `depopulate` function.

**Comment by fdelayen** [comment] 2016-09-12 09:06
I tested many things but could not figure any issue. What exactly can not be updated ?

**Comment by Zertz** [comment] 2016-09-12 11:32
I did some work on this in #298, if I recall correctly, it is triggered when you add an object with an `_id` property rather than just the id as a string.

**Comment by tro3** [comment] 2016-10-30 22:53
+1 here, and I've tracked it down.

It happens when you have an array of ObjectIds in your schema, and you are trying to update to _fewer_ items in the list using the fully-populated objects in your update.  So for example if your Litter object schema has a reference to a list of Cats, and you initially have two Cat references:

`{_id: ObjectId("12345"), cats: [ObjectId("87654"), ObjectId("54321")]}`

an attempt to PUT to `/api/v1/cats/12345`:

`{
  "_id": "12345",
  "cats": [
    {"_id": "54321", "name": "Sabian"}
  ]
}`

will result in a final list of 

`{_id: ObjectId("12345"), cats: [ObjectId("54321"), ObjectId("54321")]}`.

If you don't use the full objects and just the id strings, it works fine.  The reason for the difference: in `operations.modifyObject`, the `depoulate` function will take an array of ids (strings) and return them as-is, but will take an array of objects and return them in the form [{0:id0}, {1:id1}, ...}].  After `moredots`, the result is then put in front of a `$set` for the update.  In the above example, it will set the first item in the existing array to the new ObjectId, _but never remove the second_.

The solution would seem to be to return depopulated reference arrays as just an array of ObjectId strings, rather than the array of {index:key} pairs.  I'll work on a pull request.

**Comment by Zertz** [comment] 2016-10-30 23:14
Thanks for taking the time to track it down! I had started writing tests to figure out what was going, but want able to reproduce there issue. If you do work on a PR, please make sure to include a test.

**Comment by tro3** [comment] 2016-10-31 00:22
Of course.  I was just looking at the suite and trying to figure out where to put it.  I don't see an obvious unit test for operations, so I was going to put them under integration/update (200 cases for each of findOneAndUpdate true/false).  That ok?

**Comment by Zertz** [comment] 2016-10-31 00:36
Yeah, have a look at #298, it was my quick attempt at reproducing the issue.

**Comment by tro3** [comment] 2016-10-31 03:11
Done.  Simple implementation and tests are clean locally.  Sent pull request #316.

**Comment by tro3** [comment] 2016-10-31 03:15
Hmm.  Breaks on travis with "mongo errors".  I'll dig some more.

**Comment by tro3** [comment] 2016-10-31 04:00
Looks all all recent pull requests are failing the same mongo error tests for findOneAndUpdate=false on travis.  So I assume my changes are not the breaking factor. #317 has been submitted.

**Comment by Zertz** [comment] 2016-10-31 04:09
Yeah, don't worry about those two.

**Comment by Zertz** [comment] 2016-10-31 04:23
Don't worry about that error
On Oct 30, 2016 23:15, tro3 <notifications@github.com> wrote:Hmm.  Breaks on travis with "mongo errors".  I'll dig some more.

**Comment by b-gran** [comment] 2016-11-16 22:29
Pretty sure this is fixed now (in #305), but I don't have good test cases...

See https://github.com/florianholzapfel/express-restify-mongoose/pull/314/commits/21241f685845884d1bab73cf1caf5c6b31d37a20#diff-a73b019e16ef7c950a39b5efeed95327R10 for the fix

**Comment by tro3** [comment] 2016-11-16 23:12
I've got a fix for the same issue in #317.  Test cases are included.

**Comment by b-gran** [comment] 2016-11-17 21:43
Great!

I merged your fix and tests into #314 and everything works -- @Zertz do you want to merge these separately? Or is it alright if we bundle the fixes for both #294 and #305 into #314 ?

**Comment by Zertz** [comment] 2016-11-20 14:56
They can be bundled in the same PR as long as they are separate commits within said PR.

**Comment by tro3** [comment] 2016-12-30 01:41
@b-gran, which #314 commit did the fix go into?  I wanted to check it out.  @Zertz, should I cancel #317 if it is going into #314?.  Thanks, guys.

**Comment by anhoev** [comment] 2017-03-06 09:41
did you guys fix it ??

**Comment by gDelgado14** [comment] 2017-03-12 04:49
@anhoev did you try seeing if things are working for you now? I'm asking b/c I have similar schemas and will run into the same problem as u.

**Closed** 2017-10-07 17:51 UTC
Labels: bug, watchlist
