### ISSUE TITLE
Readonly fields

### ISSUE THREAD

**Issue by KATT** [florianholzapfel/express-restify-mongoose#202] opened 2015-12-04 14:31 UTC
Would be good to have fields that can't be changed in an update. I thought this was what `protected` was before I read the description.

For instance timestamps or other data that might be added from `.pre('save')` or elsewhere.

**Comment by Zertz** [comment] 2016-01-06 20:21
Duplicate of #185

**Closed by Zertz** 2016-01-06 20:21 UTC
Labels: duplicate
