### ISSUE TITLE
[Bug] Cannot populate property of object

### ISSUE THREAD

**Issue by GaryTowers** [florianholzapfel/express-restify-mongoose#112] opened 2015-04-14 21:31 UTC
When I try to populate a property or field of an object I get an error

[GET] api.com/games/?populate=**player_1.id**
`Cannot read property 'schema' of undefined`

Here is how my game schema looks like:
```javascript
game_schema = {
    player_1: {
        id: { type: mongoose.Schema.ObjectId, ref: 'Player' },
        score: Number
    },
    player_2: {
        id: { type: mongoose.Schema.ObjectId, ref: 'Player' },
        score: Number
    } 
}
```

But if I change my schema like this:
```javascript
game_schema = {
    player_1_id: { type: mongoose.Schema.ObjectId, ref: 'Player' }.
    player_1_score: Number,
    player_2: { type: mongoose.Schema.ObjectId, ref: 'Player' },
    player_2_score: Number,
}
```

and then make a [GET] api.com/games/?populate=**player_1_id**
the field gets correctly populated and outputted. 

Mongoose allows a property of an object to get populated normally.
`game_model.find().populate("player_1.id").exec(...)`

Why **express-restify-mongoose** wont do it that way? is this a bug?

**Comment by florianholzapfel** [comment] 2015-04-15 06:24
Your request should look like this: ```api.com/games/?populate=player_1```. Then it should work.

**Comment by florianholzapfel** [comment] 2015-04-15 12:38
Sorry, just looked again over that code. You're right. This seems to be a bug. I will look into it.

**Comment by GaryTowers** [comment] 2015-04-21 23:33
Thanks @florianholzapfel !

**Comment by Zertz** [comment] 2015-09-17 16:36
Closing this as duplicate of #137

**Closed by Zertz** 2015-09-17 16:36 UTC
Labels: duplicate

**Comment by arathael** [comment] 2015-09-18 11:27
I think the request should be:
```http
GET /Games?populate=player_1&select=player_1.id
```
