### ISSUE TITLE
Problem when making request from ajax source

### ISSUE THREAD

**Issue by LucianoGanga** [florianholzapfel/express-restify-mongoose#163] opened 2015-09-24 19:38 UTC
Hi! 

When I try to make a request to my route using ajax (through the dataTables extension), the request adds a timestamp in the URL. It changes from this: 
`/api/v1/cars/brands` 
to this
`/api/v1/cars/brands?_=1443122635616 `

so I get an error 400 (bad request) in as a response. Is there any way to ignore that parameter in restify? 

Thanks!
Luciano

**Comment by Zertz** [comment] 2015-09-24 19:51
Maybe @florianholzapfel can pitch in, but as fak as I know, there is no built-in workaround for this.

However, unknown parameters will simply be ignored in the next major release, which should be out soon.

**Comment by LucianoGanga** [comment] 2015-09-24 19:57
Thanks @Zertz ! 
I'm solving this forcing the `cache: false` parameter in the ajax request, so I don't get the timestamp in the request. But I'd like to solve it from restify. 

Anyway, I'll be glad to try that with your next major release. 

Thanks!
Luciano

**Comment by Zertz** [comment] 2015-09-25 12:56
Closing this as it is a duplicate of #155 and is solved in the upcoming release.

**Closed by Zertz** 2015-09-25 12:56 UTC
