### ISSUE TITLE
Ability to query via POST method

### ISSUE THREAD

**Issue by asaf-romano** [florianholzapfel/express-restify-mongoose#192] opened 2015-10-29 07:26 UTC
Hey there, first of all, thanks a ton for this awesome library. I cannot stress enough how much it simplified my code-base.

I've a little suggestion: some mongodb queries can be surprisingly long in their serialized form, e.g. an $in query on 1000+ _ids. These queries cannot be done via a GET request, because clients limit the url length. It'd be nice to have the ability to pass the query in POST form for such cases.

**Comment by Zertz** [comment] 2015-12-08 21:24
Usually, if you're looking for a very large set of results you would page them instead of having a huge query
 Could that work for you?

**Comment by asaf-romano** [comment] 2015-12-19 11:51
It's not that the result-set is big. Rather, the problem is that browsers set a limit on url length; so, for example, if you have an $in query matching too many _ids, the query will fail not because the response is going to be too large, but because the url is too long.

**Comment by asaf-romano** [comment] 2015-12-19 11:59
I realize though that the use case here is somewhat border-line. I wouldn't mind at all providing the solution within my router. I couldn't figure out a way to extend the API that way though.

**Comment by Zertz** [comment] 2016-01-06 20:25
Closing this for now as this is a very specific use-case and not RESTful.

We'll look into a generic way of implementing plugins sometimes in the future.

**Closed by Zertz** 2016-01-06 20:25 UTC

**Comment by ravishivt** [comment] 2016-01-06 20:42
I was just about to +1 this.  I could understand the recommendation to use paging for 1000+ IDs but the fact is that this library excels at exposing mongo's querying language, which provides an amazing amount of query flexibility. The problem is that this in turn leads to long URLs.

Copied below is a sample query that my app generated using a combination of UI filters.  This example sits at 752 characters, which falls below the recommended 2k limit but I could easily see it surpassing it when using more filters.  Being able to use POST to query data would be beneficial even if it breaks REST standards IMO.

```
https://localhost:5003/api/v1/files/?limit=3&sort=-created&populate=%5B%7B%22path%22%3A%22tags%22%2C%22match%22%3A%7B%22isEnabled%22%3Atrue%7D%7D%2C%7B%22path%22%3A%22products%22%2C%22match%22%3A%7B%22isEnabled%22%3Atrue%7D%7D%5D&query={%22products%22:[%2256465d6fcb22070d0a874b09%22,%22564124f955e98bbd33ecaaf2%22],%22tags%22:[%225641291d55e98bbd33ecab08%22,%225641292455e98bbd33ecab09%22],%22versions%22:[%22564124f955e98bbd33ecaafd%22,%22567ae85674aa9d3c547abf87%22,%22564124f955e98bbd33ecaafc%22,%22567ae85674aa9d3c547abf88%22,%22564815ca42e839b82564ebe7%22],%22releaseType%22:{%22$ne%22:[%22controlled%22]},%22size%22:{%22$gte%22:52428800},%22created%22:{%22$gte%22:%222015-12-30T08:00:00.000Z%22},%22categories%22:%22567aeba774aa9d3c547abf8c%22}
```

**Comment by Zertz** [comment] 2016-01-06 21:18
If someone has an idea on how to implement this in a clean way, please submit a PR. In the meantime, you could actually hack this into `preCreate`. Here's a rough idea:

```js
preCreate: function (req, res, next) {
  if (req.body && typeof req.body === 'object' && '_method' in req.body) {
    request.get(API_URL + '?' + qs.stringify(req.body.queryParameters), function (err, res, body) {
      // body is your data
    })
  } else {
    next()
  }
}
```

**Comment by asaf-romano** [comment] 2016-01-07 07:25
Funny. At the day you closed this, it turned out to be a real issue for the first time :) Back when I filed this as a hypothetical issue, I was worried about browsers not allowing long uris, but that was not the issue. It actually turned out that browsers are doing fine, but nginx, by default, limits url length to 8KB, meaning that if you're dealing with string guids as ids, any $in query on _id fails once the ids set exceeds about 200 items.

We ended up doing something like this:
```js
    router.post(`/extras/post-query/${model.collection.name}`,
...
                (req, res, next) =>
                {
                    // ramda's map maps the value of an object when called on an object, so this turns
                    // every body field into a get query param.
                    req.query = R.map(JSON.stringify, req.body || {});
                    // Override the url and the method, and delegate the query to the get-query route
                    req.url = `/${model.collection.name}`;
                    req.method = "GET";
                    next();
                });
```
